### ISSUE TITLE
Skipping Two Sub-words Instead of One

### ISSUE THREAD

**Issue by Berzeg** [dsandstrom/atom-subword-navigation#17] opened 2015-04-27 17:52 UTC
I updated to version 2.7.0 and I noticed a regression in which subword-navigation:move-right and subword-navigation:move-left would cause the cursor to navigate two sub-word to the right/left.

**Comment by dsandstrom** [comment] 2015-04-27 18:01
Thanks.  Can you add the text you are testing on (with expected and actual results)?

**Comment by Berzeg** [comment] 2015-04-27 18:56
Sure. I'm using "|" as the cursor in the following examples.

--

Actual Behaviour

```
|extTestFunctionName()

*subword-navigation:move-right*

extTest|FunctionName()
```

ExpectedBehaviour

```
|extTestFunctionName()

*subword-navigation:move-right*

ext|TestFunctionName()
```
--

Actual Behaviour

```
extTestFunctionNa|me()

*subword-navigation:move-left*

extTest|FunctionName()
```

ExpectedBehaviour

```
|extTestFunctionNa|me()

*subword-navigation:move-left*

ext|TestFunction|Name()
```

**Comment by dsandstrom** [comment] 2015-04-27 20:53
I can't reproduce the problem.  Also, nothing should have changed with the camel case navigation logic.   I made a change with snake case logic, but that was deployed in v2.6.  With v2.7, I just changed the way the commands are initialized.  Can you use key-binding-resolver to see what command is getting ran?

**Comment by Berzeg** [comment] 2015-04-28 14:37
I just noticed each time I disable and re-enable the package the number of sub-words skipped per command increases by 1.

e.g.

Yesterday's Behaviour

```
|extTestFunctionName()

*subword-navigation:move-right*

extTest|FunctionName()
```

After disabling and re-enabling the package once

```
|extTestFunctionName()

*subword-navigation:move-right*

extTestFunction|Name()
```

After disabling and re-enabling the package once more

```
|extTestFunctionName()

*subword-navigation:move-right*

extTestFunctionName|()
```

**Comment by dsandstrom** [comment] 2015-04-28 14:45
I'll test that when I get to work.  For now, try uninstalling, closing
atom, then reinstalling.  If that doesn't fix it, install the old version:
`apm install subword-navigation@2.6.0`.

**Comment by dsandstrom** [comment] 2015-04-28 16:58
Sorry, I can't reproduce the multiplier when disabling/enabling either.  Maybe, there is a problem when updating this package.  I would try to clean install this package: uninstall subword-navigation, close all instances of Atom, open Atom, install subword-navigation.  Let me know if that helps any.

**Comment by Berzeg** [comment] 2015-04-28 17:02
It worked after the fresh install (uninstall package, close atom, reinstall package) :confused:

**Comment by dsandstrom** [comment] 2015-04-28 17:04
That's good.  I changed the way the commands are registered.  So, the old command must be getting left over.

**Comment by Berzeg** [comment] 2015-04-28 17:11
It seems like it's registering the event listener multiple times without clearing it out afterwards. Feel free to close the issue now or when you get to investigate it a bit further.

**Closed** 2015-05-26 06:13 UTC
